# Generated by Django 3.2.5 on 2021-07-27 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=100)),
                ('service', models.CharField(max_length=100)),
                ('telephone', models.CharField(max_length=20)),
                ('appointment_date', models.CharField(max_length=20)),
            ],
        ),
    ]
